version: 2

references:
    working_directory: &working_directory
      ~/Android App werkgroep.prj

container_node: &container_node
  docker:
    - image: circleci/node:1
  working_directory: *working_directory

container_katalon: &container_katalon
  docker:
    - image: katalonstudio/katalon
  working_directory: *working_directory
  
jobs: 
  Run_test_suite1:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Update npm & Execute Katalon Studio Test Cards tab
          command: 
            - 'sudo npm install -g npm@latest' 
            - katalon-execute.sh katalon -testSuitePath="Test Suites/WebTest" -executionProfile="default" -browserType="Chrome (headless)"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report  

  Run_test_suite2:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio Test Cards tab
          command: npm install && katalon-execute.sh katalon -testSuitePath="Test Suites/SimpleTestFlow" -executionProfile="Global var" -deviceId="8C6X1JTMN" -browserType="Android"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report        
  
  Run_test_suite_collection3:
      docker:
        - image: katalonstudio/katalon
      steps:
        - checkout
        - run:
            name: Execute Katalon Studio Regression Cards tab test
            command: katalon-execute.sh katalon -retry=1 -retryFailedTestCases=true -testSuiteCollectionPath="Test Suites/Regression Cards tab test"
        - store-test_results:
            path: ./reports/report
        - store-artifacts:
            path: ./reports/report  
            
workflows:
  version: 2
  run_katalon:
    jobs:
      - Run_test_suite1:
          filters:
            branches:
              only:
      - Run_test_suite2:
          filters:
            branches:
              only:
      - Run_test_suite_collection3:
          requires:
            - Run_test_suite2
          filters:
            branches:
              only:
                

            