version: 2
jobs:
  test:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report
          
-----
  katalon_api_smoketest:
    <<: *container_katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: |
            cd testsAPI/PrimephonicAPI
            katalon-execute.sh -retry=0 -testSuiteCollectionPath="Test Suites/Smoke Tests/All End-point"
      - store-artifacts:
          path: ./tests/katalon/report

  katalon_api_regression:
    <<: *container_katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: |
            cd testsAPI/PrimephonicAPI
            katalon-execute.sh -retry=0 -testSuiteCollectionPath="Test Suites/Regression Tests/All Endpoints"
      - store-artifacts:
          path: ./tests/katalon/report   
 
 workflows:
  version: 2
  run_katalon:
    jobs:
      - katalon_api_regression:
          requires:
            - katalon_api_smoketest
          filters:
            branches:
              only:
                - Test
      - katalon_webapp_smoketest_a:
          requires:
            - katalon_api_regression
          filters:
            branches:
              only:
                - Test
      - katalon_webapp_reg_firefox_a:
          requires:
            - katalon_webapp_smoketest_a
          filters:
            branches:
              only:
                - Test
            