version: 2

references:
    working_directory: &working_directory
      ~/Android App werkgroep.prj

container_node: &container_node
  docker:
    - image: circleci/node:1
  working_directory: *working_directory

container_katalon: &container_katalon
  docker:
    - image: katalonstudio/katalon
  working_directory: *working_directory
  
jobs:
  Run_test_suite:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio Test Cards tab
          command: katalon-execute.sh katalon -retry=1 -retryFailedTestCases=true -testSuitePath="Test Suites/Test Cards tab" -executionProfile="Regressie" -deviceId="8C6X1JTMN" -browserType="Android"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report 
          
    Run_test_suite_collection:
      docker:
        - image: katalonstudio/katalon
      steps:
        - checkout
        - run:
            name: Execute Katalon Studio Regression Cards tab test
            command: katalon-execute.sh katalon -retry=1 -retryFailedTestCases=true -testSuiteCollectionPath="Test Suites/Regression Cards tab test"
        - store-test_results:
            path: ./reports/report
        - store-artifacts:
            path: ./reports/report
            
      steps:
        - checkout
        - run:
            name: Update npm
            command: 'sudo npm install -g npm@latest'
        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: Install npm wee
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
              - node_modules       

workflows:
  version: 2
  run_katalon:
    jobs:
      - Run_test_suite:
          filters:
            branches:
              only:
      - Run_test_suite_collection:
          requires:
            - Run_test_suite
          filters:
            branches:
              only:
                

            