  version: 2
  jobs:
    Run_test_suite1:
      docker:
        - image: katalonstudio/katalon
      steps:
        - checkout
        - run:
            name: Execute Katalon Studio Test Cards tab
            command: katalon-execute.sh katalon -testSuitePath="Test Suites/WebTest" -executionProfile="default" -browserType="Chrome (headless)"
        - store-test_results:
            path: ./report
        - store-artifacts:
            path: ./report
    Run_test_suite2:
      docker:
        - image: katalonstudio/katalon
      steps:
        - checkout
        - run:
            name: Execute Katalon Studio Test Cards tab
            command: katalon-execute.sh katalon -testSuitePath="Test Suites/SimpleTestFlow" -executionProfile="Global var" -deviceId="8C6X1JTMN" -browserType="Android"
        - store-test_results:
            path: ./report
        - store-artifacts:
            path: ./report
  
    Run_test_suite_collection3:
        docker:
          - image: katalonstudio/katalon
        steps:
          - checkout
          - run:
              name: Execute Katalon Studio Regression Cards tab test
              command: katalon-execute.sh katalon -retry=1 -retryFailedTestCases=true -testSuiteCollectionPath="Test Suites/Regression Cards tab test"
          - store-test_results:
              path: ./reports/report
          - store-artifacts:
              path: ./reports/report
            
  workflows:
    version: 2
    run_katalon:
      jobs:
        - Run_test_suite1:
            filters:
              branches:
                only: master
        - Run_test_suite2:
            filters:
              branches:
                only: master
        - Run_test_suite_collection3:
            requires:
              - Run_test_suite2
            filters:
              branches:
                only: master


            