version: 2

references:
    working_directory: &working_directory
      ~/Primephonic.Web

container_node: &container_node
  docker:
    - image: circleci/node:8
  working_directory: *working_directory

container_katalon: &container_katalon
  docker:
    - image: katalonstudio/katalon
  working_directory: *working_directory


deployment_template: &deployment_template
  docker:
    - image: circleci/python:3.5
  working_directory: *working_directory

  steps:
    - checkout
    - attach_workspace:
        at: *working_directory
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run:
        name: Install the AWS cli, Upload to EB & clear cloudfront cache
        command: |
          mkdir /home/circleci/.aws
          echo "[default]\naws_access_key_id=${AWS_KEY_ID}\naws_secret_access_key=${!AWS_KEY_SECRET}\n" > /home/circleci/.aws/config
          export PATH=/home/circleci/.local/bin:$PATH
          pip install awscli --upgrade --user
          pip install awsebcli --upgrade --user
          aws configure set aws_access_key_id ${AWS_KEY_ID}
          aws configure set aws_secret_access_key ${!AWS_KEY_SECRET}
          export AWS_CREDENTIAL_FILE=/home/circleci/.aws/config
          eb --version
          eb init "${AWS_EBS_APP}" -p "Node.js" --region ${AWS_EBS_REGION}
          eb deploy ${AWS_EBS_ENV}
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id ${AWS_CDF_ID} --paths '/*'

jobs:
  katalon_api_smoketest:
    <<: *container_katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: |
            cd testsAPI/PrimephonicAPI
            katalon-execute.sh -retry=0 -testSuiteCollectionPath="Test Suites/Smoke Tests/All End-point"
      - store-artifacts:
          path: ./tests/katalon/report

  katalon_api_regression:
    <<: *container_katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: |
            cd testsAPI/PrimephonicAPI
            katalon-execute.sh -retry=0 -testSuiteCollectionPath="Test Suites/Regression Tests/All Endpoints"
      - store-artifacts:
          path: ./tests/katalon/report

  katalon_webapp_smoketest_a:
    <<: *container_katalon
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio Smoke test for accept-environment
          command: |
            cd tests/katalon
            katalon-execute.sh -retry=0 -testSuiteCollectionPath="Test Suites/Smoke test headless"
      - store-artifacts:
          path: ./tests/katalon/report

  katalon_webapp_reg_firefox_a:
    <<: *container_katalon
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio simple regression firefox accept
          command: |
            cd tests/katalon
            katalon-execute.sh -retry=1 -retryFailedTestCases=true -testSuitePath="Test Suites/Full regression suite" -executionProfile="Acceptatie omgeving-Regressie" -browserType="Firefox (headless)"
      - reportFileName:
          path: ./tests/katalon/report
  katalon_webapp_reg_firefox_b:
    <<: *container_katalon
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio simple regression firefox accept
          command: |
            cd tests/katalon
            katalon-execute.sh -retry=1 -retryFailedTestCases=true -testSuitePath="Test Suites/My Music view" -executionProfile="Accept omgeving- My Music" -browserType="Firefox (headless)"
      - store-artifacts:
          path: ./tests/katalon/report

  katalon_webapp_reg_firefox_c:
    <<: *container_katalon
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio simple regression firefox accept
          command: |
            cd tests/katalon
            katalon-execute.sh -retry=1 -retryFailedTestCases=true -testSuitePath="Test Suites/My Music rename and delete" -executionProfile="Acceptatie omgeving-Regressie" -browserType="Firefox (headless)"
      - store-artifacts:
          path: ./tests/katalon/report

  katalon_webapp_full_reg_chrome_firefox_a:
    <<: *container_katalon
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio full regression chrome and firefox accept
          command: |
            cd tests/katalon
            katalon-execute.sh -retry=0 -testSuiteCollectionPath="Test Suites/Multi browser test ALL headless"
      - store-artifacts:
          path: ./tests/katalon/report

  katalon_webapp_multi_sub_type_chrome_firefox_a:
    <<: *container_katalon
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio multi subscriptions type chrome and firefox accept
          command: |
            cd tests/katalon
            katalon-execute.sh -retry=0 -reportFileName="Different subscriptions" -testSuiteCollectionPath="Test Suites/Different subscriptions test headless"
      - store-artifacts:
          path: ./tests/katalon/report


  ## BUILD WEBAPP
  build_webapp_dev:
    <<: *container_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build the web app
          command: |
            export VUE_APP_API_ENDPOINT=https://api-dev.primephony.com
            export VUE_APP_AUTH0_DOMAIN=auth-dev.primephony.com
            export VUE_APP_AUTH0_CLIENTID=doXF0PAf02WLUIReeTkaiVFLPtQFBXHX
            export VUE_APP_AUTH0_REDIRECT_URL=https://play-dev.primephony.com/callback
            export VUE_APP_TRACKING_CODE=UA-56265075-2
            export VUE_APP_ACCOUNT_ENDPOINT=http://account-dev.primephony.com
            export VUE_APP_APPLE_APP_ID=1437138559
            export VUE_APP_ROBOTS_NOINDEX=noindex
            npm install
            npm run build:play
            mkdir dist/.well-known
            cp site-associations/assetlinks-dev.json dist/.well-known/assetlinks.json
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *working_directory
          paths:
            - node_modules
            - dist

  build_webapp_test:
    <<: *container_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build the web app
          command: |
            export VUE_APP_API_ENDPOINT=https://api-test.primephony.com
            export VUE_APP_AUTH0_DOMAIN=auth-test.primephony.com
            export VUE_APP_AUTH0_CLIENTID=doXF0PAf02WLUIReeTkaiVFLPtQFBXHX
            export VUE_APP_AUTH0_REDIRECT_URL=https://play-test.primephony.com/callback
            export VUE_APP_TRACKING_CODE=UA-56265075-2
            export VUE_APP_GTM_CODE=GTM-53ZW9JH
            export VUE_APP_ACCOUNT_ENDPOINT=http://account-test.primephony.com
            export VUE_APP_APPLE_APP_ID=1437138559
            export VUE_APP_DISABLE_TRACKING=TRUE
            export VUE_APP_ROBOTS_NOINDEX=noindex
            npm install
            npm run build:play
            cp site-associations/apple-app-site-association.play-test dist/apple-app-site-association
            cp site-associations/manifest.json.play-test dist/manifest.json
            mkdir dist/.well-known
            cp site-associations/assetlinks-test.json dist/.well-known/assetlinks.json
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *working_directory
          paths:
            - node_modules
            - dist

  build_webapp_acceptance:
    <<: *container_node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Build the web app
          command: |
            export VUE_APP_API_ENDPOINT=https://api-play-accept.primephonic.com
            export VUE_APP_AUTH0_DOMAIN=auth-acc.primephonic.com
            export VUE_APP_AUTH0_CLIENTID=RyDIwmvXMHOQq0e4CGvahXvXujh3FdMt
            export VUE_APP_AUTH0_REDIRECT_URL=https://play-accept.primephonic.com/callback
            export VUE_APP_TRACKING_CODE=UA-56265075-2
            export VUE_APP_GTM_CODE=GTM-53ZW9JH
            export VUE_APP_ACCOUNT_ENDPOINT=http://account-accept.primephonic.com
            export VUE_APP_APPLE_APP_ID=1369949771
            export VUE_APP_DISABLE_TRACKING=TRUE
            export VUE_APP_ROBOTS_NOINDEX=noindex
            npm install
            npm run build:play
            cp site-associations/apple-app-site-association.play-accept dist/apple-app-site-association
            cp site-associations/manifest.json.play-accept dist/manifest.json
            mkdir dist/.well-known
            cp site-associations/assetlinks-acc.json dist/.well-known/assetlinks.json
      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *working_directory
          paths:
            - node_modules
            - dist

  build_webapp_production:
    <<: *container_node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Build the web app
          command: |
            export VUE_APP_API_ENDPOINT=https://api-play.primephonic.com
            export VUE_APP_AUTH0_DOMAIN=auth.primephonic.com
            export VUE_APP_AUTH0_CLIENTID=iyEF5wnwdOlchbUdLhF7dJTt6FJRrJXg
            export VUE_APP_AUTH0_REDIRECT_URL=https://play.primephonic.com/callback
            export VUE_APP_TRACKING_CODE=UA-56265075-3
            export VUE_APP_GTM_CODE=GTM-53ZW9JH
            export VUE_APP_ACCOUNT_ENDPOINT=http://account.primephonic.com
            export VUE_APP_APPLE_APP_ID=1311521674
            npm install
            npm run build:play
            cp site-associations/apple-app-site-association.play dist/apple-app-site-association
            cp site-associations/manifest.json.play dist/manifest.json
            mkdir dist/.well-known
            cp site-associations/assetlinks-prod.json dist/.well-known/assetlinks.json
      - save_cache:
          paths:
          - node_modules_PLAY
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *working_directory
          paths:
            - node_modules
            - dist

  ## DEPLOY WEBAPP
  deploy_webapp_dev:
    <<: *deployment_template
    environment:
      AWS_KEY_ID: AKIAIJASPUQ7EILGXGOQ
      AWS_KEY_SECRET: AWS_SECRET_DEV_TEST
      AWS_EBS_REGION: eu-west-2
      AWS_EBS_APP: primephonic-webssr
      AWS_EBS_ENV: primephonic-webssr-dev
      AWS_CDF_ID: E1HHQ57M2DXV96

  deploy_webapp_test:
    <<: *deployment_template
    environment:
      AWS_KEY_ID: AKIAIJASPUQ7EILGXGOQ
      AWS_KEY_SECRET: AWS_SECRET_DEV_TEST
      AWS_EBS_REGION: eu-west-2
      AWS_EBS_APP: primephonic-webssr
      AWS_EBS_ENV: primephonic-webssr-test
      AWS_CDF_ID: E2X3RZK7BFFYIO

  deploy_webapp_acceptance:
    <<: *deployment_template
    environment:
      AWS_KEY_ID: AKIAJR5J3NPSMC5QFJGA
      AWS_KEY_SECRET: AWS_SECRET_ACC_PROD
      AWS_EBS_REGION: eu-central-1
      AWS_EBS_APP: Primephonic Web SSR
      AWS_EBS_ENV: PrimephonicWebSSR-accept
      AWS_CDF_ID: E3BKVE4CXH0USL

  deploy_webapp_production:
    <<: *deployment_template
    environment:
      AWS_KEY_ID: AKIAJR5J3NPSMC5QFJGA
      AWS_KEY_SECRET: AWS_SECRET_ACC_PROD
      AWS_EBS_REGION: eu-central-1
      AWS_EBS_APP: Primephonic Web SSR
      AWS_EBS_ENV: PrimephonicWebSSR-prod
      AWS_CDF_ID: E3FWSSD5CITT8N

workflows:
  version: 2
  build_and_deploy_production:
    jobs:
      - build_webapp_production:
          filters:
            tags:
              only:
                - /.*/
            branches:
              only:
                - /^hotfix\/.*/
      - hold_webapp_deployment:
          type: approval
          requires:
            - build_webapp_production
          filters:
            tags:
              only:
                - /.*/
            branches:
              only:
                - /^hotfix\/.*/
      - deploy_webapp_production:
          requires:
            - hold_webapp_deployment
          filters:
            tags:
              only:
                - /.*/
            branches:
              only:
                - /^hotfix\/.*/
  build_and_deploy_acceptance:
    jobs:
      - build_webapp_acceptance:
          filters:
            branches:
              only:
                - /^release\/.*/
                - /^hotfix\/.*/
      - hold_webapp_deployment:
          type: approval
          requires:
          - reportFileName
          - build_webapp_acceptance
          filters:
            branches:
              only:
                - /^release\/.*/
                - /^hotfix\/.*/
      - deploy_webapp_acceptance:
          requires:
            - hold_webapp_deployment
          filters:
            branches:
              only:
                - /^release\/.*/
                - /^hotfix\/.*/
  build_and_deploy_to_test:
    jobs:
      - build_webapp_test:
          filters:
            branches:
              only:
                - master
      - deploy_webapp_test:
          requires:
            - build_webapp_test
          filters:
            branches:
              only:
                - master
  run_katalon:
    jobs:
      - katalon_api_smoketest:
          filters:
            branches:
              only:
                - Test
      - katalon_api_regression:
          requires:
            - katalon_api_smoketest
          filters:
            branches:
              only:
                - Test
      - katalon_webapp_smoketest_a:
          requires:
            - katalon_api_regression
          filters:
            branches:
              only:
                - Test
      - katalon_webapp_reg_firefox_a:
          requires:
            - katalon_webapp_smoketest_a
          filters:
            branches:
              only:
                - Test
      - katalon_webapp_full_reg_chrome_firefox_a:
          requires:
            - katalon_webapp_reg_firefox_a
          filters:
            branches:
              only:
                - Test
      - katalon_webapp_multi_sub_type_chrome_firefox_a:
          filters:
            branches:
              only:
                - Test
  build_and_deploy_to_dev:
    jobs:
      - build_webapp_dev:
          filters:
            branches:
              ignore:
                - /^release\/.*/
      - hold_webapp_deployment:
          type: approval
          requires:
            - build_webapp_dev
          filters:
            branches:
              ignore:
                - /^release\/.*/
      - deploy_webapp_dev:
          requires:
            - hold_webapp_deployment
          filters:
            branches:
              ignore:
                - /^release\/.*/

